import { test, expect } from '@playwright/test';

test('shows error for incorrect password (Generated by Playwright MCP & GitHub Copilot)', async ({ page }) => {
  // dynamic incorrect password: use env var if provided, otherwise generate one
  const incorrectPassword = process.env.INCORRECT_PASSWORD ?? `incorrect-${Math.random().toString(36).slice(2, 8)}`;

  await page.goto('http://practicetestautomation.com/practice-test-login/');

  // Fill username and password using accessible labels when available
  await page.getByLabel('Username').fill('student');
  await page.getByLabel('Password').fill(incorrectPassword);

  // Click the submit button (match common button texts case-insensitively)
  await page.getByRole('button', { name: /submit|sign in|log in|login/i }).first().click();

  // Verify error message is visible and has exact text
  const error = page.locator('#error');
  await expect(error).toBeVisible();
  await expect(error).toHaveText('Your password is invalid!');

  // Take a screenshot of the result into the repository screenshots folder
  await page.screenshot({ path: `screenshots/login-error-${Date.now()}.png`});

  await page.close();
});
