import { test, expect } from '@playwright/test';

    const BASE_URL = 'https://practicetestautomation.com/practice-test-login/';

test('Negative Login - Incorrect Username (Generated by Playwright Codegen)', async ({ page }) => {

    const incorrectUsername = 'student' + Math.random().toString(36).slice(2, 10);

    // Step 1: Navigate to the login page
        await page.goto(BASE_URL);
    
    // Step 2: Attempt to log in with an incorrect username
        await page.getByRole('textbox', { name: 'Username' }).click();
        await page.getByRole('textbox', { name: 'Username' }).fill(incorrectUsername);

    // Step 3: Attempt to log in with an correct password
        await page.getByRole('textbox', { name: 'Password' }).click();
        await page.getByRole('textbox', { name: 'Password' }).fill('Password123');

    // Step 4: Click the submit button
        await page.getByRole('button', { name: 'Submit' }).click();

    // Step 5: Verify the error message is displayed
        await expect(page.locator('#error')).toBeVisible();
    
    // Add screenshot
    await page.screenshot({ path: 'screenshots/negative-login-generated.png' });

    await page.close();
});